server:
    port: 8000

spring:
    application:
        name: customer
    datasource:
        username: 'premukkoji'
        url: jdbc:postgresql://localhost:5432/customer
        password: 'password'
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: 'true'
        hibernate:
            ddl-auto: update
        show-sql: 'true'
    zipkin:
        base-url: http://localhost:9411

eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            default-zone: http://localhost:8761/eureka