server:
    port: 8001

spring:
    application:
        name: fraud
    datasource:
        username: 'premukkoji'
        url: jdbc:postgresql://localhost:5432/fraud
        password: 'password'
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: 'true'
        hibernate:
            ddl-auto: update
        show-sql: 'true'